services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - 82:81
      - 80:80
      - 443:443
    environment:
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: npm
      DB_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_MYSQL_NAME: npm
    volumes:
      - /mnt/Vol1-Z2/Apps_Data/nginx-proxy-manager/data:/data
      - /mnt/Vol1-Z2/Apps_Data/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  db:
    image: mariadb:latest
    container_name: nginx-proxy-manager_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /mnt/Vol1-Z2/Apps_Data/nginx-proxy-manager/db:/var/lib/mysql
    restart: unless-stopped

networks: {}