services:
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    environment:
      PHOTOPRISM_UID: 568
      PHOTOPRISM_GID: 568
      PHOTOPRISM_TIMEZONE: Europe/Bucharest
      PHOTOPRISM_DATABASE_DRIVER: mysql
      PHOTOPRISM_DATABASE_DSN: photoprism:${MYSQL_PASSWORD}@tcp(db:3306)/photoprism
      PHOTOPRISM_ORIGINALS_LIMIT: 5000
      PHOTOPRISM_HTTP_COMPRESSION: true
      PHOTOPRISM_WORKERS: 2
      PHOTOPRISM_SITE_URL: ${PHOTOPRISM_SITE_URL}
      PHOTOPRISM_PUBLIC: false
    volumes:
      - /mnt/Vol1-Z2/Apps_Data/photoprism/App_Storage:/photoprism/storage
      - /mnt/Vol1-Z2/Apps_Data/photoprism/Photoprism_Import:/photoprism/import
      - /mnt/Vol1-Z2/Apps_Data/photoprism/Photoprism_Originals:/photoprism/originals
    ports:
      - 2342:2342
    restart: unless-stopped

  db:
    image: mariadb:10.6
    container_name: photoprism_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /mnt/Vol1-Z2/Apps_Data/photoprism/database:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped

networks: {}